# Generated by Django 5.2.8 on 2025-11-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='expertise',
            new_name='experience',
        ),
    ]
